# Generated by Django 5.2.7 on 2025-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0002_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
