# Generated by Django 5.2.8 on 2025-11-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_board_app', '0002_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
